### ISSUE TITLE
Not in NPM

### ISSUE THREAD

**Issue by d-Pixie** [jtefera/merge-files-webpack#1]
I get this when I try to install the plugin:

    $ npm install merge-text-webpack-plugin -save-dev
    npm ERR! code E404
    npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/merge-text-webpack-plugin
    npm ERR! 404
    npm ERR! 404  'merge-text-webpack-plugin' is not in the npm registry.
    npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
    npm ERR! 404
    npm ERR! 404 Note that you can also install from a
    npm ERR! 404 tarball, folder, http url, or git url.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/pixie/.npm/_logs/2017-03-21T12_16_56_402Z-debug.log

**Comment by jtefera** [comment]
Sorry! I put the wrong name in the instructions. 
The correct command is:

    npm install merge-files-webpack-plugin  --save-dev
